[build]
  functions = "netlify/functions"
  publish = "build"

[[redirects]]
  from = "/noisy-plate/*"
  to = "/noisy-plate/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"